# Generated by Django 4.0 on 2021-12-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('hobbies', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('submitter', models.ManyToManyField(to='accounts.AccountUser')),
            ],
        ),
    ]
