# Generated by Django 4.0 on 2021-12-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_pet_profile_pic_alter_pet_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='submitter',
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
