# Generated by Django 4.0 on 2021-12-18 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('adoptions', '0003_remove_pet_submitter_alter_pet_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='submitter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountuser'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
