# Generated by Django 4.0 on 2021-12-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pets_posted', models.CharField(blank=True, max_length=300)),
                ('password', models.CharField(default='anim1610', max_length=300)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('first_name', models.CharField(default='anim', max_length=300)),
                ('last_name', models.CharField(default='malvat', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
